FROM ubuntu:20.04

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ADD ./ /sumstats_imputation

ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y git && \
    apt-get install python3-pip --yes

# need to upgrade pip to install jass deps
RUN pip3 install --upgrade pip && \
    pip3 install -Iv git+https://gitlab.pasteur.fr/statistical-genetics/JASS_Pre-processing && \
    pip3 install -Iv git+https://gitlab.pasteur.fr/statistical-genetics/raiss
